### PR TITLE
Integrate new deploy script

### PR DESCRIPTION
**Pull request by BobTheBotMaker**
There is a new scalr side deploy script for ttmscalr to integrate with. The primary reason for the new script is to integrate support for Node, bug fixes and to integrate learnings over the past year. The script has a new name TTM-Launcher and operates via command line options. All ttmscalr tasks were upgraded to use the new script.

Some unused and deprecated functions of scalr/ttmscalr were also removed.

### CODE REVIEW

**Comment by TheJefe** [comment]
I had a chat with Andre, and as a result, this is what I want to test

- [ ] Deploy Apangea
- [ ] Deploy Reporting
- [ ] Deploy Lesson player
- [ ] Deploy Live Teaching
- [ ] Shutdown Sidekiq
- [ ] Restart Apangea
- [ ] Restart Reporting
- [ ] Deploy --hard
- [ ] Scale up

**Comment by BobTheBotMaker** [comment]
For live teaching be sure to use my aws-port branch and you can push it to aws-live-teaching-dev for use on the dev farm.

**Comment by TheJefe** [comment]
the `shutdown:sidekiq` command is failing

```sh
./bin/ttmscalr shutdown:sidekiq -f dw-qa
ARE YOU SURE YOU WANT TO SHUTDOWN SIDEKIQ? (yes to confirm) yes
Executing shutdown for role:  sidekiq (ID: 82781)
Script executed... polling for logs from a server.
..
FAIL (1 of 1 servers).
sidekiq.1 => exit code: 1
```

The scalr logs show

```
Message:

STDERR:
stdin: is not a tty
2015-04-30 11:34:58 Role is: Sidekiq
2015-04-30 11:34:58 Cannot determine apps. TTM_FARM_APPS is empty and -a not specified


STDOUT:
/usr/local/bin/scalr-scripting.1430393698.69/TTM_Launcher -S 

Usage:

/usr/local/bin/scalr-scripting.1430393698.69/TTM_Launcher -a application[,application,...] -i|l[|r] -K|-k key
/usr/local/bin/scalr-scripting.1430393698.69/TTM_Launcher -a application[,application,...] -R
/usr/local/bin/scalr-scripting.1430393698.69/TTM_Launcher -S

Option descriptions:
-a applications to operate on. Typically github repos, ex. -a aws-dev,aws-lesson-player
If the script is executed as a scalr event (BeforeHostUp or RebootComplete) it will look
for applications in the TTM_FARM_APPS farm level global variable
-c Delete redis keys left behind by a failed deployment. Use with -k to provide the deploy key.
-i Install the listed applications
-l Lauch applications
-r Hard restart before launch
-S Shutdown the application for the current farm role. Not valid with any other options.
-K Do not lock the farm with a deploy key. Only use if you know what you are doing
-k Unique Deploy key to lock the farm and track deployment across servers
```

**Comment by BobTheBotMaker** [comment]
Only the dev farm has the needed env vars setup. If you tell me what farm you want to use I can set the env vars on them or you can test on dev.

**Comment by TheJefe** [comment]
I have acquired the dev farm

**Comment by BobTheBotMaker** [comment]
Dev Farm for the Dev Farm GODS!

**Comment by TheJefe** [comment]
@BobTheBotMaker same issue is occurring on the dw-dev farm, the same way.

**Comment by BobTheBotMaker** [comment]
My bad. env variable set.

**Comment by TheJefe** [comment]
that fixed it! thanks!

**Comment by TheJefe** [comment]
Ok, I tried to deploy lesson player to dev, with this command

```
ttmscalr deploy leson-player -f dev
Deploying application leson-player to farm dev
Are you SURE you pushed to the AWS dev repo?
Waiting a few seconds to jog your memory. Ctrl-C if you're not sure! .....OK, let's go!
Cleanup command if things go wrong:
  $ ttmscalr deploy:cleanup dev -k 67bb05e4-28de-40d9-b0e1-4963e67c32b2
6 6 6 6 6 0
COMPLETE: SOME FAILED.
========================================
RailsAppServer: failed: 1
FAIL:
** Type: Scripting; Script: TTM_Launcher; Event: Executed via API; Exit: 10; Exec time: 60.0 sec
Uncategorized failure
(see log message)

LOG:
No log message [Exit code: 10]
========================================
Bunchball: failed: 1
FAIL:
** Type: Scripting; Script: TTM_Launcher; Event: Executed via API; Exit: 10; Exec time: 60.0 sec
Uncategorized failure
(see log message)

LOG:
No log message [Exit code: 10]
========================================
DevDebug: failed: 1
FAIL:
** Type: Scripting; Script: TTM_Launcher; Event: Executed via API; Exit: 10; Exec time: 60.0 sec
Uncategorized failure
(see log message)

LOG:
No log message [Exit code: 10]
========================================
Reports: failed: 1
FAIL:
** Type: Scripting; Script: TTM_Launcher; Event: Executed via API; Exit: 10; Exec time: 60.0 sec
Uncategorized failure
(see log message)

LOG:
No log message [Exit code: 10]
========================================
Sidekiq: failed: 1
FAIL:
** Type: Scripting; Script: TTM_Launcher; Event: Executed via API; Exit: 10; Exec time: 60.0 sec
Uncategorized failure
(see log message)

LOG:
No log message [Exit code: 10]
========================================
SystemWatcher: failed: 1
FAIL:
** Type: Scripting; Script: TTM_Launcher; Event: Executed via API; Exit: 10; Exec time: 60.0 sec
Uncategorized failure
(see log message)

LOG:
No log message [Exit code: 10]
```

 and got this error in scalr

```
STDERR:
stdin: is not a tty
2015-05-01 12:39:54 Role is: Web
2015-05-01 12:40:25 Waiting for deployment sync.
2015-05-01 12:40:41 Installing aws-leson-player to /var/www/
2015-05-01 12:40:42 Source aws-leson-player and Target aws-dev Repo do not match
```

**Comment by BobTheBotMaker** [comment]
:(

**Comment by BobTheBotMaker** [comment]
You spelled lesson incorrectly. It has two s :)
There is no way for me to know if a repo is valid or not unless I put the full name of all repos in the script.

**Comment by TheJefe** [comment]
womp womp, thanks

**Comment by seejee** [comment]
Deploy the Lesion Player! (eww)

**Pull request merged**
