### PR TITLE
make psql tunnel open tunnel and psql in same command

### PR DESCRIPTION
**Pull request by joelmccracken**
Instead of requiring the user to copy/paste a long command, just run it immediately.

### CODE REVIEW

**Comment by joelmccracken** [comment]
There's actually an issue with this where calling C-c in the middle of a psql command kills the whole thing entirely, instead of canceling the command.

**Comment by joelmccracken** [comment]
I think this version is good!

**Review by TheJefe — COMMENTED** [review]
Very nice! This LGTM, CR and QA wise.

One comment though, some people like to use the tunnel, then use PGAdmin to write and execute queries rather then psql.  Can we add an option for that? It could probably simply run `open /Applications/PGAdmin` or something like that? or just a way to say wether to run the psql command or not?

**Comment by joelmccracken** [comment]
You got it, Pontiac! FYI, one could run this and connect as usual -- the tunnel is still open.

How should it work? can you tell me specifically what you'd l.ike it to do?

**Comment by TheJefe** [comment]
yea, the only problem with it always automatically opening psql , if you don't use psql, you may not know to exit with `\q`.

As far as how it "should work", let me get back to you

**Pull request closed without merging**
